version: '3.8'
services: 
  mysql-db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: fancyPassword
      MYSQL_DATABASE: fancyDatabase
  adminer:
    depends_on:
      - mysql-db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  go-app:
    depends_on:
      - mysql-db
    build: .
    environment:
      DB_URL: mysql-db
      DB_USER: root
      DB_PASS: fancyPassword
      DB_DATABASE: fancyDatabase

#networks:
#  external:
#    external: true

